### ISSUE TITLE
Point Load Test

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#8] opened 2019-02-26 19:50 UTC
I have seen the Point Load Test Index (Is50 result) in the list of DIGGS Test Properties.  This then means the Point Load Test is tied to a sample.  

A point load test is often performed in the field and can also be done in the lab.  So, the question is should this be tied to a specific sample or is it something just performed at a specific depth?  In the lab it is definitely tied to the Sample.  When tested in the field, from a fundamental perspective I can see how it should be tied to a sample, but I can also see where it shouldn't be tied to a sample because the "sample" that was theoretically tested, now is not available to the laboratory because the sample was destroyed in the testing process. So, having a "sample" that is not available to the lab for scheduling and testing potentially makes the data management process more confusing and allow users to schedule something that isn't possible to test.

Any thoughts are appreciated.

**Comment by AC107** [comment] 2019-02-26 20:11
if the sample is destroyed by testing in the field that is fine then no tests would be assigned in the lab on that sample.  But it is still a test on a sample rather than a test performed instu at some depth?  If it is done on a portion of the sample, does it become a trial?  or the sample is just subdivided?

**Comment by sdeaton75** [comment] 2019-02-26 20:43
It is a test on something that came from a sampling activity (which you might call a sample but that is also potentially confusing and misleading).  This same concept applies to doing a pocket penetrometer or torvane on soil at the end of a Shelby Tube. Technically that is a Sampling Activity.  You pull the Shelby Tube out of the ground. In this scenario, you did the activity and then push the pocket pen into the end of the tube. I haven't done anything to subdivide this into a "sample" that will be sent to the lab.  Yet, I would have to in order to do the Pocket Pen?

Regarding the scheduling, there would be nothing to prevent a user from scheduling tests on the sample that was destroyed.  That is the problem. Someone would have to know that in the first place. So this could lead to scheduling on a sample that doesn't exist and labs would then not know and waste lots of time looking for a non-existent sample.

For the point load test, it is not performed insitu, it is done on a portion of the material from the sampling activity or a subdivided piece of the material.

**Comment by dponti** [comment] 2019-03-01 16:44
Any test performed on a sample collected in the field, whether the test is performed in the field or lab, is, as far as the schema structure is concerned, a laboratory test. Lab tests can reference the specimens (which derive from Samples) upon which the test is performed. In the example you gave, a sample was collected in the field (shelby tube sample) and a point load test was done on the end of the sample giving an Is50 value. The Is50 value goes into the results portion of the Test element and the location property of the test would hold the specific depth of the test (depth at the bottom of the shelby tube sample). The test's procedure property would then contain the point load test object – to identify the procedure used to obtain the Is50 value, and within this object, you would instantiate a specimen object that points to the shelby tube sample using the sampleRef property. Alternatively, you are not required to identify the specimen in a case where the sample where a test is performed in the field was not recorded - as long as the depth of the test is recorded in the Test element, this is all that's required.

**Comment by dponti** [comment] 2019-03-01 17:02
Point load and pocket/hand penetrometer test procedures are not included in the current 2.5.a version of Diggs on Github. They did exist in an earlierversion inherited from 2.0.b, but were removed during our vetting process, were not identified as priority tests at our meeting in Harrisburg, and have not yet been added back. As they are simple test procedures, (with no additional properties other than what all test procedures carry), there is no reason not to add them back in at this time.

However, before I do anything, I have a question. The earlier  schema had a LabPenetrometerTest procedure and a PointLoadTest procedure - both of which are essentially the same, schema structure-wise - they have no unique properties other than standard lab test properties. The PointLoadTest currently is defined as producing an Is50 value, and the LabPenetrometerTest produces both peak and residual undrained shear strength results.

Is the PointLoadTest and the LabPenetrometerTest really the same thing? - eg measurement of compressive and/or shear strength using a hand or bench mounted penetrometer device? If these are different tests, how so?

Either way, it would make sense to create both "lab" and "in-situ" versions of the tests to distinguish between a test done on a sample collected from (say) a borehole and one done in-situ (such as on the side wall of a test pit).

Please chime in and I'll construct appropriate versions of the(se) tests for your review.

**Comment by panars** [comment] 2020-06-05 15:34
The PointLoadTest is the Point Load Strength Index test on rock, I believe (ASTM D8121). This is not the same as the pocket or hand penetrometer test, which is done on soil, so they should have different procedures.  I am a little confused about the LabPenetrometerTest and whether this was intended to be the pocket penetrometer test.  I don't see how you get a residual undrained shear strength from a pocket penetrometer test. This test is problematic in the sense that there is no standard specification for it that I am aware of (at least not ASTM). The pocket penetrometer is mentioned in OSHA 29, Part 1926 Subpart P for excavations.  Since the point load strength index is different, I recommend we add it to the schema now, and discuss the pocket penetrometer some more to figure out how that is added.

**Comment by panars** [comment] 2020-06-05 15:52
I also recommend closing this issue related to the point load strength index test if Dan is satisified. The Pocket/hand penetrometer should be its own separate issue.

**Comment by dponti** [comment] 2020-06-08 00:17
Point Load Strength Test procedure added to development version (currently 2.5.b) as a laboratory test procedure. As mentioned previously, if a specimen can be recorded for the test or not, as long as the depth to the sample is known, that's fine. Optionally, a specimen from a sample can be identified and associated with the test.

**Closed by dponti** 2020-06-08 00:17 UTC
Labels: enhancement, question
